### ISSUE TITLE
Object 'var.obs' not defined

### ISSUE THREAD

**Issue by dschlaep** [bellland/SDM.Virtual.Species_Bell.Schlaepfer#1]
The object ''var.obs' is used, but not defined. This in the else clause of the 'file.exists(ftemp <- file.path(dir.in, filename.saveTypeData))' condition: lines 195/196 of the master branch.

I guess it should be something like var.obs <- c("LnP", "MinT")?

**Comment by dschlaep** [comment]
Ok, I think I got it: 'var.obs' is one of the variance types for the function 'calc_ObservationsFromProbabilities'

**Comment by bellland** [comment]
Oops, I changed the name of that after I proved to myself that it worked. By that time, I had the workspace. This should be "errors". I have corrected and am testing it now. Should be able to commit it to the repository shortly.

**Comment by bellland** [comment]
Daniel,

I will be pushing a fix shortly. I commented on the thread for reference (I changed the name of the object).

Dave
